version: "3"
services:

  proxy:
    image: luisguilermes/simpleform_proxy
    links:
      - simpleformapp
    ports:
      - "80:80"
    networks:
      - frontend
    environment:
      - NGINX_HOST=proxy
      - NGINX_PROXY=http://app:9090
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  app:
    image: luisguilermes/simpleform_app
    environment:
      ENV: PROD
    networks:
      - backend

networks:
  frontend:
  backend: